language: python
deploy:
  provider: heroku
  api_key:
    secure: gZujkTFGetPTAjjQiaserOgvzIOXUk9GG8++53xobIdRlYZ+XqTliyhIK7u1Y8LuckErVY44FEfXhPMYTs7/MCJg+lcWy9fi/HX6ggshNPykRi92DAnh2HsQ4LWZbw/mzFvwVMy7GlKpEpmO4uqgctKZt4q033T9kaKdfQfLTkHANw9zNEysZZfWOXT4a2EZAe2jcqPaEpf3luvhSkZdEczeUMYSvphoVbK/ngnFbo8pJGhZTWMdgBJJwToRdqrWDXZn/HH2/Spfi7ZJ15/sDlClntm6vI1x8PUcs3y8C4dNXzoBrL7GIjDo5N7GGqHQ5pX6LCq7/TXKI9Vq0OqKDonYBS9eRtgtgKzIs9OFVBgEhnExob0dHRacwJmClLM5QThlm9mMIbIAe3D9Mw6n5zJiIVi9sCVz3lfU1alkIlqMmpOS6SP3O28K3SWFmUFNjk5UPNiLfQkds779vfKqlHecrTz9T341s+joerO9RKKPka1xOe3GX7mn3sbdgt+CY3uLkrdqC6AaBoS+OBe6k5Vr7Wa8owD31H+uN7WJe6XqI6nbrhcm2P7RKYbq0/7ksqGsZ2HYaKrhSDClAA5VkaX1hHZ8YPRLYX78p1VfJdolIkA7LoNA4bu8Ul73adub8scnoe/xerxmd/84rHo3rrO7NEVhCZaU+avPwo7U87E=
  app: suxor-github-stats
